version: '3.5'

services:
  app-web:  
    build: ./web
    ports:
      - "8081:8080"
    networks:
      - meu-app
    depends_on:
      - app-db


  app-db:  
    image: postgres:9.4-alpine
    volumes:
      - app-db2:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project_test
    networks:
      - meu-app

networks:
  meu-app:

volumes:
  app-db2:
